# Generated by Django 5.0.2 on 2024-02-19 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Engineer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('year_of_join', models.IntegerField(max_length=4)),
                ('enginner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='api.engineer')),
            ],
        ),
        migrations.DeleteModel(
            name='Note',
        ),
    ]
