# Generated by Django 5.0.2 on 2024-02-19 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_engineer_experience_delete_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='year_of_join',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
