# Generated by Django 5.0.2 on 2024-02-19 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_experience_year_of_join'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engineer',
            name='slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
    ]
